services:
  vllm-qwen3:
    image: vllm/vllm-openai:latest
    container_name: vllm-qwen3
    ports:
      - "8000:8000"
    volumes:
      - ./hf-cache:/root/.cache/huggingface
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - VLLM_ATTENTION_BACKEND=FLASHINFER
      # Pass additional environment variables from .env if needed
      - VLLM_MODEL=${VLLM_MODEL}
      - VLLM_HOST=${VLLM_HOST}
      - VLLM_PORT=${VLLM_PORT}
      - VLLM_MAX_MODEL_LEN=${VLLM_MAX_MODEL_LEN}
      - VLLM_MAX_NUM_SEQS=${VLLM_MAX_NUM_SEQS}
      - VLLM_KV_CACHE_DTYPE=${VLLM_KV_CACHE_DTYPE}
      - VLLM_DTYPE=${VLLM_DTYPE}
      - VLLM_API_KEY=${VLLM_API_KEY}
      # Optional: GPU memory utilization
      - VLLM_GPU_MEMORY_UTILIZATION=${VLLM_GPU_MEMORY_UTILIZATION:-0.9}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command:
      - --model
      - ${VLLM_MODEL}
      - --host
      - ${VLLM_HOST}
      - --port
      - ${VLLM_PORT}
      - --max-model-len
      - ${VLLM_MAX_MODEL_LEN}
      - --max_num_seqs
      - ${VLLM_MAX_NUM_SEQS}
      - --kv-cache-dtype
      - ${VLLM_KV_CACHE_DTYPE}
      - --dtype
      - ${VLLM_DTYPE}
      - --api-key
      - ${VLLM_API_KEY}
      # Uncomment below if you want to use variable GPU memory utilization
      # - --gpu-memory-utilization
      # - ${VLLM_GPU_MEMORY_UTILIZATION}

    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ./webui-data:/app/backend/data
    depends_on:
      - vllm-qwen3
    restart: unless-stopped
    